# Generated by Django 3.2.5 on 2021-08-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['pk']},
        ),
    ]
